version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-site
    restart: always
    expose:
      - "3000"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - nextjs
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
